T_max: 64
a2a_radius: 80
agent_occlusion_ratio: 0.0
devices: 1
dropout: 0.1
duration: 10
flip_p: 0.5
hidden_dim: 128
l2a_radius: 80
lane_occlusion_ratio: 0.2
lr: 0.0005
max_epochs: 64
num_attn_layers: 3
num_future_steps: 30
num_heads: 8
num_historical_steps: 10
num_hops: 4
num_modes: 6
num_visible_steps: 3
num_workers: 4
persistent_workers: true
pin_memory: true
root: /data6/yaochengbo/HPNet/HPNet-main/interaction_dataset/multi/
shuffle: true
train_batch_size: 2
val_batch_size: 2
warmup_epochs: 4
weight_decay: 0.0001
